# Automatic conversion maps for long names to short abbreviations
# This allows users to provide full names while maintaining naming conventions

locals {
  # Environment name conversions
  environment_conversions = {
    "development" = "dev"
    "staging"     = "stg"
    "production"  = "prod"
    "testing"     = "test"
    "qa"          = "qa"
    "uat"         = "uat"
    "demo"        = "demo"
    "sandbox"     = "sbx"
    "preprod"     = "pprd"
    "preproduction" = "pprd"
    "dr"          = "dr"
    "disaster-recovery" = "dr"
    "backup"      = "bkp"
    "shared"      = "shrd"
    "common"      = "cmn"
    "management"  = "mgmt"
    "monitoring"  = "mon"
    "security"    = "sec"
    "identity"    = "id"
    "network"     = "net"
    "hub"         = "hub"
    "spoke"       = "spk"
  }
  
  # Azure region conversions
  region_conversions = {
    "eastus"          = "eus"
    "eastus2"         = "eus2"
    "westus"          = "wus"
    "westus2"         = "wus2"
    "westus3"         = "wus3"
    "centralus"       = "cus"
    "southcentralus"  = "scus"
    "northcentralus"  = "ncus"
    "westcentralus"   = "wcus"
    "eastus2euap"     = "eus2e"
    "southeastasia"   = "sea"
    "eastasia"        = "ea"
    "australiaeast"   = "aue"
    "australiasoutheast" = "ause"
    "australiacentral" = "auc"
    "australiacentral2" = "auc2"
    "brazilsouth"     = "brs"
    "brazilsoutheast" = "brse"
    "canadacentral"   = "cac"
    "canadaeast"      = "cae"
    "chinaeast"       = "cne"
    "chinaeast2"      = "cne2"
    "chinanorth"      = "cnn"
    "chinanorth2"     = "cnn2"
    "chinanorth3"     = "cnn3"
    "francecentral"   = "frc"
    "francesouth"     = "frs"
    "germanycentral"  = "gec"
    "germanynorth"    = "gen"
    "germanynortheast" = "gene"
    "germanywestcentral" = "gewc"
    "japaneast"       = "jpe"
    "japanwest"       = "jpw"
    "koreacentral"    = "krc"
    "koreasouth"      = "krs"
    "northeurope"     = "neu"
    "westeurope"      = "weu"
    "norwayeast"      = "noe"
    "norwaywest"      = "now"
    "southafricanorth" = "san"
    "southafricawest" = "saw"
    "switzerlandnorth" = "szn"
    "switzerlandwest" = "szw"
    "uaenorth"        = "uan"
    "uaecentral"      = "uac"
    "uksouth"         = "uks"
    "ukwest"          = "ukw"
    "usgovarizona"    = "usga"
    "usgovtexas"      = "usgt"
    "usgovvirginia"   = "usgv"
    "usdodcentral"    = "usdc"
    "usdodeast"       = "usde"
    "usgovlowa"       = "usgl"
    "usgoviowa"       = "usgi"
    "swedencentral"   = "swc"
    "swedensouth"     = "sws"
    "polandcentral"   = "plc"
    "indiacentral"    = "inc"
    "indiasouth"      = "ins"
    "indiawest"       = "inw"
    "italynorth"      = "itn"
    "spaincentral"    = "spc"
    "israelcentral"   = "isc"
    "qatarcentral"    = "qac"
  }
  
  # Convert environment name to abbreviation
  environment_abbr = lookup(local.environment_conversions, lower(var.environment), var.environment)
  
  # Convert region name to abbreviation
  region_abbr = lookup(local.region_conversions, lower(var.region), var.region)
}
